name: Android CI

on:
  push:
    branches: [ "clean", "main", "feature/**" ]
  pull_request:
    branches: [ "clean", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Instala Android SDK y herramientas de línea de comandos
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages (platforms/build-tools) and accept licenses
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "cmdline-tools;latest"
          yes | sdkmanager --licenses

      # Cache de Gradle (opcional pero acelera)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug
        run: ./gradlew clean assembleDebug --stacktrace
