name: Android CI

on:
  push:
    branches: [ "clean", "main", "feature/**" ]
  pull_request:
    branches: [ "clean", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug
        run: ./gradlew clean assembleDebug --stacktrace
